### ISSUE TITLE
Unable to browse music - there was a problem connecting

### ISSUE THREAD

**Issue by alexjans** [public-broadcasting/bbc-sounds-community-edition-for-sonos#4]
Cannot browse or play any feed at present

**Comment by public-broadcasting** [comment]
Hello @alexjans,

Thank you for lettings us know. 

Our ISP is currently suffering from a [DDoS attack](https://en.wikipedia.org/wiki/Denial-of-service_attack), which is why we have temporarily moved the service to another provider. Unfortunately, the new server collapsed directly under the load.

The service is now back and running and we will continue to monitor the situation. We will be setting up a status page shortly with more information on the health of the service.

Apologize for the inconvenience and hope we have overcome the worst.

Thank you.

**Comment by public-broadcasting** [comment]
Hello again,

We got an all clear from the ISP, which means we are not expecting any interruptions anymore.

We have now set up a status page so that you can keep up to date with future disruptions:
https://status.streamurl.link/public-broadcasting/

We will probably carry out maintenance work on February 12, 2024, including an adjustment of the DNS entry. Detailed information with a lead time of one week will be announced on the status page when the plans become more concrete.

We hope to have informed you well.

**Comment by alexjans** [comment]
Perfect thanks for your update!

Kind regards

Alex Jans
